// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ParcialWebApi.Models;

public partial class Solicitud
{
    public int Numero { get; set; }

    public DateTime? Fecha { get; set; }

    public string Solicita { get; set; }

    public string Estado { get; set; }

    public string Detalle { get; set; }

    public int TipoCambio { get; set; }

    public virtual TipoCambio TipoCambioNavigation { get; set; }
}