// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ParcialWebApi.Models;

public partial class SolicitudesContext : DbContext
{
    public SolicitudesContext(DbContextOptions<SolicitudesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Solicitud> Solicitudes { get; set; }

    public virtual DbSet<TipoCambio> TipoCambios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Solicitud>(entity =>
        {
            entity.HasKey(e => e.Numero);

            entity.Property(e => e.Numero)
                .ValueGeneratedNever()
                .HasColumnName("numero");
            entity.Property(e => e.Detalle)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("detalle");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("estado");
            entity.Property(e => e.Fecha)
                .HasColumnType("datetime")
                .HasColumnName("fecha");
            entity.Property(e => e.Solicita)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("solicita");
            entity.Property(e => e.TipoCambio).HasColumnName("tipoCambio");

            entity.HasOne(d => d.TipoCambioNavigation).WithMany(p => p.Solicitudes)
                .HasForeignKey(d => d.TipoCambio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Solicitudes_TipoCambio");
        });

        modelBuilder.Entity<TipoCambio>(entity =>
        {
            entity.ToTable("TipoCambio");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}