// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ParcialWebApi.Models;

public partial class TipoCambio
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Solicitud> Solicitudes { get; set; } = new List<Solicitud>();
}